"""Thin re-export shim for backward compatibility — canonical types now live in automarkov.domain.canonical."""

from automarkov.domain.canonical import (
    MAX_CANONICAL_DOCUMENT_BYTES,
    MAX_JSON_NESTING_DEPTH,
    MAX_JSON_NODES,
    MAX_JSON_PAYLOAD_BYTES,
    MAX_SAFE_INTEGER,
    CanonicalJsonValue,
    CanonicalPayloadCodec,
    ConfidenceCanonicalFloat,
    FrozenSequence,
    FrozenStringMapping,
    NonNegativeCanonicalFloat,
    NonNegativeSafeCanonicalInt,
    PositiveSafeCanonicalInt,
    ProbabilityCanonicalFloat,
    SafeCanonicalInt,
    StrictCanonicalFloat,
    StrictFalse,
    StrictTrue,
    canonical_json_bytes,
    parse_canonical_document,
    parse_json_payload,
    require_registered_model_number_contract,
    validate_and_measure_raw_json_tree,
)

__all__ = [
    "MAX_CANONICAL_DOCUMENT_BYTES",
    "MAX_JSON_NESTING_DEPTH",
    "MAX_JSON_NODES",
    "MAX_JSON_PAYLOAD_BYTES",
    "MAX_SAFE_INTEGER",
    "CanonicalJsonValue",
    "CanonicalPayloadCodec",
    "ConfidenceCanonicalFloat",
    "FrozenSequence",
    "FrozenStringMapping",
    "NonNegativeCanonicalFloat",
    "NonNegativeSafeCanonicalInt",
    "PositiveSafeCanonicalInt",
    "ProbabilityCanonicalFloat",
    "SafeCanonicalInt",
    "StrictCanonicalFloat",
    "StrictFalse",
    "StrictTrue",
    "canonical_json_bytes",
    "parse_canonical_document",
    "parse_json_payload",
    "require_registered_model_number_contract",
    "validate_and_measure_raw_json_tree",
]
